export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SET_DATE_FILTER = 'SET_DATE_FILTER'
export const CHANGE_ARTICLES_SELECTOR = 'CHANGE_ARTICLES_SELECTOR';